### ISSUE TITLE
chef/debian-7.6 not found

### ISSUE THREAD

**Issue by oknet** [tko/vagrant-wdmycloud#2]
hi, I'm trying to get a wdmycloud package build envirment depond on this project.
# but I got error during vagrant up:

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'chef/debian-7.6' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'chef/debian-7.6' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/chef/debian-7.6"]
# Error: The requested URL returned error: 404 Not Found

which debian box can be used for it ?

**Comment by tko** [comment]
Basically any debian or debian derivative box should be usable. I would think https://atlas.hashicorp.com/debian/boxes/wheezy64 should be good these days but I have not tried it myself.
